name: Testing Niffler
on:
  push:
    branches: [master, dev]

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3
        run: |
          apt-get update -y -q
          apt-get install -q -y python3 
          apt-get install -q -y python3-pip unzip
      - name: Install Dependencies
        run: |
          pip3 install -U pip
          pip3 install -r ./requirements-dev.txt
          unzip ./tests/data.zip -d ./tests/
      - name: Run Tests
        run: |
          echo "Running Unit Tests"
          pytest ./tests/unit

  run_integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3
        run: |
          apt-get update -y -q
          apt-get install -q -y python3 
          apt-get install -q -y python3-pip unzip
      - name: Install Dependencies
        run: |
          pip3 install -U pip
          pip3 install -r ./requirements-dev.txt
          unzip ./tests/data.zip -d ./tests/
      - name: Run Tests
        run: |
          echo "Running Integration Tests"
          pytest ./tests/integration
